# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: $$e^{i\pi}+1$$ 
email: cfs@etotheipiplus.one
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog. I'm a software developer by profession, a math nerd by passion, and
  a teacher by delusion. Many posts on this blog will focus on chapters from popular math
  textbooks. I will paraphrase the chapter and introduce some ways of thinking about the
  material. I believe math is all about discovering natural intuitions, so I'll avoid
  making claims about what is the correct method. Instead, I'll present many methods for
  your consideration. Don't be surprised if I take tangents into math history, puzzles, and
  general musings. I may even toss in some code here and there. Read the parts you enjoy,
  skip the rest, and please let me know if you learn something.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://etotheipiplus.one" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

host: etotheipiplus.one
disqus:
  shortname: etotheipiplus-one

